### ISSUE TITLE
Script bombing out: Probably a dependency issue / Can setup a user for you on my server if needed.

### ISSUE THREAD

**Issue by sgoggins** [Euphorbium/netdoctor-scraper#1]
[gogginss@sociotechnical-missouri-edu scrape]$ python netdoctor.py
processing page 1
Traceback (most recent call last):
  File "netdoctor.py", line 23, in <module>
    thread = html.parse(url+'/p'+str(pager))
  File "/usr/lib64/python2.7/site-packages/lxml/html/**init**.py", line 769, in parse
    return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:70175)
  File "parser.pxi", line 1749, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102290)
  File "parser.pxi", line 1775, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:102554)
  File "parser.pxi", line 1679, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:101589)
  File "parser.pxi", line 1110, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:97041)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91494)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92680)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91941)
IOError: Error reading file 'http://forums.netdoctor.co.uk/discussion/101540/delayed-periods-due-to-sex/p1': failed to load HTTP resource

**Comment by sgoggins** [comment]
I will pay you for debugging.

**Comment by Euphorbium** [comment]
Ok, give me the login info in private message.

**Comment by Euphorbium** [comment]
Are you running it on pythonanywhere ?

**Comment by sgoggins** [comment]
Sociotechnical.missouri.edu

Sean P. Goggins
Associate Professor
Director, Data Science and Analytics Masters Program
DSA Masters: http://dsa.missouri.edu 

University of Missouri
(816) 368-1364
The iSchool at Missouri http://ischool.missouri.edu 
MU Informatics Institute http://muii.missouri.edu 
Computer Science  http://engineering.missouri.edu/cs/ 
http://www.seangoggins.net
visit: http://www.sociotech.net
visit: http://www.datafactories.org 

"I force people to have coffee with me, just because I don't trust that a friendship can be maintained without any other senses besides a computer or cellphone screen.”
— John Cusack

"Never doubt that a small group of thoughtful, committed citizens can change the world. Indeed, it is the only thing that ever has."
-- Margaret Mead

"Probably the most dangerous thing about college education, at least in my own case, is that it enables my tendency to over-intellectualize stuff, to get lost in abstract arguments inside my head instead of simply paying attention to what’s going on right in front of me." 
— David Foster Wallace

On April 5, 2016 at 10:00:52 AM, Juozas Masiulis (notifications@github.com) wrote:

Are you running it on pythonanywhere ?

**Comment by sgoggins** [comment]
Username juozas

Sean P. Goggins
Associate Professor
Director, Data Science and Analytics Masters Program
DSA Masters: http://dsa.missouri.edu 

University of Missouri
(816) 368-1364
The iSchool at Missouri http://ischool.missouri.edu 
MU Informatics Institute http://muii.missouri.edu 
Computer Science  http://engineering.missouri.edu/cs/ 
http://www.seangoggins.net
visit: http://www.sociotech.net
visit: http://www.datafactories.org 

"I force people to have coffee with me, just because I don't trust that a friendship can be maintained without any other senses besides a computer or cellphone screen.”
— John Cusack

"Never doubt that a small group of thoughtful, committed citizens can change the world. Indeed, it is the only thing that ever has."
-- Margaret Mead

"Probably the most dangerous thing about college education, at least in my own case, is that it enables my tendency to over-intellectualize stuff, to get lost in abstract arguments inside my head instead of simply paying attention to what’s going on right in front of me." 
— David Foster Wallace

On April 5, 2016 at 10:00:52 AM, Juozas Masiulis (notifications@github.com) wrote:

Are you running it on pythonanywhere ?

**Comment by Euphorbium** [comment]
Seems like their server simply could not hold up the traffic. Currently they are offline. I should add some delay between requests.

**Comment by sgoggins** [comment]
Yes.  Probably taking 100 records and then pausing for 2 minutes ... For
all of them is a good idea.

_Sean P. Goggins__Associate Professor_
_Director, Data Science and Analytics Masters Program_
_DSA Masters: http://dsa.missouri.edu http://dsa.missouri.edu/ *
*University of Missouri_
_(816) 368-1364 <//(816)%20368-1364>_
_The iSchool at Missouri http://ischool.missouri.edu
http://ischool.missouri.edu/ *
*MU Informatics Institute http://muii.missouri.edu
http://muii.missouri.edu/ *
*Computer Science  http://engineering.missouri.edu/cs/
http://engineering.missouri.edu/cs/ *
*http://www.seangoggins.net_ http://www.seangoggins.net/
_visit: http://www.sociotech.net http://www.sociotech.net/_
*visit: http://www.datafactories.org http://www.datafactories.org/ *

_"I force people to have coffee with me, just because I don't trust that a
friendship can be maintained without any other senses besides a computer or
cellphone screen.”_
— John Cusack

"_Never doubt that a small group of thoughtful, committed citizens can
change the world. Indeed, it is the only thing that ever has_."
-- Margaret Mead

*"Probably the most dangerous thing about college education, at least in my
own case, is that it enables my tendency to over-intellectualize stuff, to
get lost in abstract arguments inside my head instead of simply paying
attention to what’s going on right in front of me." *
— David Foster Wallace
